### ISSUE TITLE
No bypass at all

### ISSUE THREAD

**Issue by Nexuzzzz** [ThusInfinity/Dark-Matter-Layer-7-DDoS#11]
This doesn't bypass rate limiting, nor does it bypasses WAF's. Still, good tool tho

**Comment by BGInfinityX** [comment]
The bypasses got patched 1 month after the release, but i have another bypasses capable of instant downing WAF, im not gonna release it since it would be dangerous and i know peoples dont care about "Terms of use: Only for testing".

**Comment by ThusInfinity** [comment]
@silkyearth  @Nexuzzzz 

this is the error im getting after i run it

> [>>>] Starting the attack [<<<]
> Traceback (most recent call last):
> File "/home/kali/Dark-Matter-Layer-7-DDoS/DarkMatter.py", line 58, in
> send2attack() #61 lines for the most powerful attack, cool?
> File "/home/kali/Dark-Matter-Layer-7-DDoS/DarkMatter.py", line 56, in send2attack
> mp.start() #Magic Starts
> File "/usr/lib/python3.9/multiprocessing/process.py", line 121, in start
> self._popen = self._Popen(self)
> File "/usr/lib/python3.9/multiprocessing/context.py", line 224, in _Popen
> return _default_context.get_context().Process._Popen(process_obj)
> File "/usr/lib/python3.9/multiprocessing/context.py", line 277, in _Popen
> return Popen(process_obj)
> File "/usr/lib/python3.9/multiprocessing/popen_fork.py", line 19, in init
> self._launch(process_obj)
> File "/usr/lib/python3.9/multiprocessing/popen_fork.py", line 65, in _launch
> child_r, parent_w = os.pipe()
> OSError: [Errno 24] Too many open file

ulimit -n 99999 or ulimit -n 999999 will fix this

**Comment by ThusInfinity** [comment]
> > > > put down the instructions on how to use the tool plz. python2 3? etc @ThusInfinity
> > > 
> > > 
> > > `python3 DarkMatter.py` or `python DarkMatter.py `
> > 
> > 
> > this is the error im getting after i run it
> > [>>>] Starting the attack [<<<] Traceback (most recent call last): File "/home/kali/Dark-Matter-Layer-7-DDoS/DarkMatter.py", line 58, in send2attack() #61 lines for the most powerful attack, cool? File "/home/kali/Dark-Matter-Layer-7-DDoS/DarkMatter.py", line 56, in send2attack mp.start() #Magic Starts File "/usr/lib/python3.9/multiprocessing/process.py", line 121, in start self._popen = self._Popen(self) File "/usr/lib/python3.9/multiprocessing/context.py", line 224, in _Popen return _default_context.get_context().Process._Popen(process_obj) File "/usr/lib/python3.9/multiprocessing/context.py", line 277, in _Popen return Popen(process_obj) File "/usr/lib/python3.9/multiprocessing/popen_fork.py", line 19, in **init** self._launch(process_obj) File "/usr/lib/python3.9/multiprocessing/popen_fork.py", line 65, in _launch child_r, parent_w = os.pipe() OSError: [Errno 24] Too many open files
> 
> the tool sucks, you are better off using HULK or any other professional stress testing tool

This tool is professional aswell, it's just not well documented but the v2 is coming so all these problems will be fixed and new bypasses (Cloudflare bypass v4 is one of the new bypasses) will be on the 2nd version
