### ISSUE TITLE
Suspending

### ISSUE THREAD

**Issue by Dreambigxz** [ThusInfinity/Dark-Matter-Layer-7-DDoS#12]
Mehn my system met the requirement why doe sit hang it

**Comment by BGInfinityX** [comment]
Can u send an screenshot of the error?

**Comment by Dreambigxz** [comment]
I will appreciate if you chat me on telegram @teckwise

**Comment by ThusInfinity** [comment]
Sorry, but i cant do it at the moment :( You can take an screenshot and upload on image upload site and send me the link here
