### ISSUE TITLE
Возможность отправить определенный пакет

### ISSUE THREAD

**Issue by Timezero1** [ThusInfinity/Dark-Matter-Layer-7-DDoS#16]
- [(LIST l="qwerty"/)]  is this package infinitely possible to send? And what possibilities will be with an 8-core processor at a channel of 300 mb / s. This package is used to bypass waf it is legitimate

**Comment by ThusInfinity** [comment]
Yes; on 8 core 300mb/s would be "medium" speed; If you increase to 1 g-bit the speed will be very faster! I recommend you to use this packet (package) in the new version (I Will release the v2 in less than 2 weeks)

**Comment by Timezero1** [comment]
Thank you very much for the answer, I'm waiting for a new version then
