### ISSUE TITLE
Help!!!! DDOs

### ISSUE THREAD

**Issue by leo562** [ThusInfinity/Dark-Matter-Layer-7-DDoS#17]
Why when I enter the site domain in the tester dstats measured the attack of 20 million requests for example: Https:/181.173.174.8 when I type in
IP/Domain: 181.173.174 port:80 and the attack goes on. When I enter for example a website https://stresser.network / in the panel I write stresser.network and specify port 80, then the attack does not go why??????

**Comment by ThusInfinity** [comment]
Dont use "https://" or "/", use only the domain "stresser.network"

for example:

IP/Domain: stresser.network
port: 80

My script automatically adds "http://" to the domain right after you insert it
