### ISSUE TITLE
Does this work on windows?

### ISSUE THREAD

**Issue by Notsalgia** [ThusInfinity/Dark-Matter-Layer-7-DDoS#19]
I downloaded it and ran it, but it did not DDOS it just kept repeating the message: "detecting system"

**Comment by Notsalgia** [comment]
and also it crashed my pc

**Comment by ThusInfinity** [comment]
Windows is not 100% compatible with it, also, according to our README.md you should not attack using your computer, run it on a Dedicated Server or VPS
